repos:
-   repo: local
    hooks:
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types:
        - python
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
        - python
    -   id: isort
        name: isort
        entry: isort
        language: system
        types:
        - python
    -   id: bandit
        name: bandit
        entry: bandit --ini .bandit
        language: system
    -   id: black
        name: black
        entry: black
        language: system
        types:
        - python
